export const FETCH_POPULAR_REVIEWS_PENDING = 'FETCH_POPULAR_REVIEWS_PENDING';
export const FETCH_POPULAR_REVIEWS_SUCCESS = 'FETCH_POPULAR_REVIEWS_SUCCESS';

export const FETCH_POPULAR_REVIEWERS_PENDING = 'FETCH_POPULAR_REVIEWERS_PENDING';
export const FETCH_POPULAR_REVIEWERS_SUCCESS = 'FETCH_POPULAR_REVIEWERS_SUCCESS';
