export const FETCH_MOVIES_PENDING = 'FETCH_MOVIES_PENDING';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';

export const FETCH_FEATURED_PENDING = 'FETCH_FEATURED_PENDING';
export const FETCH_FEATURED_SUCCESS = 'FETCH_FEATURED_SUCCESS';

export const FETCH_MOVIE_DETAIL_PENDING = 'FETCH_MOVIE_DETAIL_PENDING';
export const FETCH_MOVIE_DETAIL_SUCCESS = 'FETCH_MOVIE_DETAIL_SUCCESS';
export const CLEAR_MOVIE_DETAIL = 'CLEAR_MOVIE_DETAIL';

export const CREATE_MOVIE_SUCCESS = 'CREATE_MOVIE_SUCCESS';
export const UPDATE_MOVIE_SUCCESS = 'UPDATE_MOVIE_SUCCESS';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const MOVIE_ADMIN_FAILURE = 'MOVIE_ADMIN_FAILURE';
